### ISSUE TITLE
Plans Plans

### ISSUE THREAD

**Issue by Taki21** [ImagicalDevs/SurvivalGames-ULTIMATE#2]
**PLANS HERE**

**Comment by Taki21** [comment]
**Ok ... SO Here is the plan or jobs for some people if u wanna change let me know
@ImagicalGamer: Schedule Repeating Tasks I suck at dat also can u do sg setup process like tap block saves to config ? thx
@Taki21 @TheKnightGamer #SomebodyElse:
We do the rest of the functions SG file  **

**Comment by TheKnightGamer** [comment]
First let work on setup

**Comment by Taki21** [comment]
ya

**Comment by Taki21** [comment]
@TheKnightGamer  I see i know wut to do now

**Comment by Taki21** [comment]
using a property like @ImagicalGamer did in his SG we are able to access people's touch on blocks to set to config on command as this is a continuation from the OnCommand to the onInteract() function
Brilliant!

**Comment by remotevase** [comment]
You really think that @ImagicalGamer is gonna ditch his SG plugin and work on this one? Wow. No offense, but you must be really dumb...

**Comment by Taki21** [comment]
um we are just asking him for help and dont need it anyway figured it out myself and ya im so dumb that i dont know php lol

**Comment by Taki21** [comment]
Wait a sec...How do i know what even php is? Thats Strange...

**Comment by Taki21** [comment]
I must be really smart to even know what PHP is even though I dont even know what it is xD

**Comment by Taki21** [comment]
THATS IT IM GOING FROM PHP PROFESSOR To NEW SPECIE OF TAKIS

**Comment by Taki21** [comment]
No Offense But Everyone is Stupid For Not Reading and maybe less of me
Before I accuse or say something I READ WHAT THE SITUATION IS THEN I SAY WHAT I WANT SO PLEASE READ AROUND BEFORE ACCUSING ME OR SAYING ANYTHING

**Comment by Taki21** [comment]
THis is closed useless

**Comment by TheKnightGamer** [comment]
@Taki21 use this as a setup:
{	
	public $data;
	
	private static $object = null;
	
	public static function getInstance(){
		return self::$object;
	}

	public function onEnable() {
		$this->api = EconomyAPI::getInstance();
		$this->getServer()->getPluginManager()->registerEvents($this,$this);
		$this->getServer()->getScheduler()->scheduleRepeatingTask(new CallbackTask([$this,"gameTimber"]),20);
		@mkdir($this->getDataFolder(), 0777, true);
		
		# Custom Config Saving
		$this->saveResource("points.yml");
		$this->points = new Config($this->getDataFolder(). "points.yml", Config::YAML);
		
		# Custom Points Config Saving
		$this->saveResource("config.yml");
		$this->config = new Config($this->getDataFolder(). "config.yml", Config::YAML, array());
				
		if($this->config->exists("lastpos"))
		{
			$this->sign=$this->config->get("sign");
			$this->pos1=$this->config->get("pos1");
			$this->pos2=$this->config->get("pos2");
			$this->pos3=$this->config->get("pos3");
			$this->pos4=$this->config->get("pos4");
			$this->pos5=$this->config->get("pos5");
			$this->pos6=$this->config->get("pos6");
			$this->pos7=$this->config->get("pos7");
			$this->pos8=$this->config->get("pos8");
			$this->pos9=$this->config->get("pos9");
			$this->pos10=$this->config->get("pos10");
			$this->pos11=$this->config->get("pos11");
			$this->pos12=$this->config->get("pos12");
			$this->pos13=$this->config->get("pos13");
			$this->pos14=$this->config->get("pos14");
			$this->pos15=$this->config->get("pos15");
			$this->pos16=$this->config->get("pos16");
			$this->pos17=$this->config->get("pos17");
 			$this->pos18=$this->config->get("pos18");
 			$this->pos19=$this->config->get("pos19");
 			$this->pos20=$this->config->get("pos20");
 			$this->pos21=$this->config->get("pos21");
 			$this->pos22=$this->config->get("pos22");
 			$this->pos23=$this->config->get("pos23");
 			$this->pos24=$this->config->get("pos24");			
			$this->lastpos=$this->config->get("lastpos");
			$this->signlevel=$this->getServer()->getLevelByName($this->config->get("sign")["level"]);
			$this->sign=new Vector3($this->sign["x"],$this->sign["y"],$this->sign["z"]);
			$this->pos1=new Vector3($this->pos1["x"]+0.5,$this->pos1["y"],$this->pos1["z"]+0.5);
			$this->pos2=new Vector3($this->pos2["x"]+0.5,$this->pos2["y"],$this->pos2["z"]+0.5);
			$this->pos3=new Vector3($this->pos3["x"]+0.5,$this->pos3["y"],$this->pos3["z"]+0.5);
			$this->pos4=new Vector3($this->pos4["x"]+0.5,$this->pos4["y"],$this->pos4["z"]+0.5);
			$this->pos5=new Vector3($this->pos5["x"]+0.5,$this->pos5["y"],$this->pos5["z"]+0.5);
			$this->pos6=new Vector3($this->pos6["x"]+0.5,$this->pos6["y"],$this->pos6["z"]+0.5);
			$this->pos7=new Vector3($this->pos7["x"]+0.5,$this->pos7["y"],$this->pos7["z"]+0.5);
			$this->pos8=new Vector3($this->pos8["x"]+0.5,$this->pos8["y"],$this->pos8["z"]+0.5);
			$this->pos9=new Vector3($this->pos9["x"]+0.5,$this->pos9["y"],$this->pos9["z"]+0.5);
			$this->pos10=new Vector3($this->pos10["x"]+0.5,$this->pos10["y"],$this->pos10["z"]+0.5);
			$this->pos11=new Vector3($this->pos11["x"]+0.5,$this->pos11["y"],$this->pos11["z"]+0.5);
                        $this->pos12=new Vector3($this->pos12["x"]+0.5,$this->pos12["y"],$this->pos12["z"]+0.5);
                        $this->pos13=new Vector3($this->pos13["x"]+0.5,$this->pos13["y"],$this->pos13["z"]+0.5);
                        $this->pos14=new Vector3($this->pos14["x"]+0.5,$this->pos14["y"],$this->pos14["z"]+0.5);
                        $this->pos15=new Vector3($this->pos15["x"]+0.5,$this->pos15["y"],$this->pos15["z"]+0.5);
                        $this->pos16=new Vector3($this->pos16["x"]+0.5,$this->pos16["y"],$this->pos16["z"]+0.5);
                        $this->pos17=new Vector3($this->pos17["x"]+0.5,$this->pos17["y"],$this->pos17["z"]+0.5);
                        $this->pos18=new Vector3($this->pos18["x"]+0.5,$this->pos18["y"],$this->pos18["z"]+0.5);
                        $this->pos19=new Vector3($this->pos19["x"]+0.5,$this->pos19["y"],$this->pos19["z"]+0.5);
                        $this->pos20=new Vector3($this->pos20["x"]+0.5,$this->pos20["y"],$this->pos20["z"]+0.5);
                        $this->pos21=new Vector3($this->pos21["x"]+0.5,$this->pos21["y"],$this->pos21["z"]+0.5);
                        $this->pos22=new Vector3($this->pos22["x"]+0.5,$this->pos22["y"],$this->pos22["z"]+0.5);
                        $this->pos23=new Vector3($this->pos23["x"]+0.5,$this->pos23["y"],$this->pos23["z"]+0.5);
                        $this->pos24=new Vector3($this->pos24["x"]+0.5,$this->pos24["y"],$this->pos24["z"]+0.5);
			$this->lastpos=new Vector3($this->lastpos["x"]+0.5,$this->lastpos["y"],$this->lastpos["z"]+0.5);
		}
		if(!$this->config->exists("endTime"))
		{
			$this->config->set("endTime",180);
		}
		if(!$this->config->exists("gameTime"))
		{
			$this->config->set("gameTime",300);
		}
			if(!$this->config->exists("prefix"))
		{
			$this->config->set("prefix","Game");
		
		}
			
		if(!$this->config->exists("waitTime"))
		{
			$this->config->set("waitTime",180);
		}
		
		$this->endTime=(int)$this->config->get("endTime");//????
		$this->gameTime=(int)$this->config->get("gameTime");//????
		$this->waitTime=(int)$this->config->get("waitTime");//????
		$this->prefix=$this->config->get("prefix");//????
		$this->gameStatus=0;//???? 
		$this->lastTime=(int)0;//????
		$this->players=array();//???????
		$this->SetStatus=array();//????
		$this->all=0;//??????
		$this->config->save();
		$pm = $this->getServer()->getPluginManager();
		if(!($this->money = $pm->getPlugin("EconomyAPI"))
        && !($this->money = $pm->getPlugin("PocketMoney")))			{
			$this->getServer()->getLogger()->info(TextFormat::RED. "[SG-U] ----Warning!!!----");
			$this->getServer()->getLogger()->info(TextFormat::RED. "[SG-U] Economy isn't installed!");
			$this->getServer()->getLogger()->info(TextFormat::RED. "[SG-U] Please install Economy or PocketMoney to enable SG");
		} else {
			$this->getServer()->getLogger()->info(TextFormat::DARK_BLUE."[SG-U] Using Money System From... ".
											 TextFormat::YELLOW.$this->money->getName()." v".
											 $this->money->getDescription()->getVersion());
											 }
		$this->getServer()->getLogger()->info(TextFormat::BLUE."[SG-U] SurvivalGame-Ulitamate Has Been Enable");
		$this->getServer()->getLogger()->info(TextFormat::BLUE."[SG-U] By: ImagicalDevs");
		$this->getServer()->getLogger()->info(TextFormat::BLUE."[SG-U] Config Loaded !");
		$this->getServer()->getLogger()->info(TextFormat::BLUE."[SG-U] Point Loaded !");

**Comment by Taki21** [comment]
thx xD i was apart of dat xD
