### ISSUE TITLE
Closing

### ISSUE THREAD

**Issue by Taki21** [ImagicalDevs/SurvivalGames-ULTIMATE#4]
I will delete dis repo
we dont need replicas of SG...Plus @ImagicalGamer  's SG Plugin is way better...Im gonna help em out! xD

**Comment by TheKnightGamer** [comment]
Why it just SG I will take over man and make it better and put kits that are editable in kits.yml Setup in Config.yml and the sgdata.yml

**Comment by Taki21** [comment]
Yay Ok!

**Comment by Taki21** [comment]
We are keep goin on!

**Comment by TheKnightGamer** [comment]
Ok
